#  The Numpy library

In [16]:
import numpy as np #import

In [17]:
#create numpy array
np.array([1,2,3])

array([1, 2, 3])

In [18]:
a = np.array([[1,2,3],[4,5,6]]) #create multi dimensional array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#shape of the array
a.shape

(2, 3)

In [20]:
#evenly spaced values between the interval
b = np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [21]:
#create new shape of data
b.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [174]:
#get evenly spaced numbers between specified interval
c = np.linspace(1,5,20)
c

array([ 1.        ,  1.21052632,  1.42105263,  1.63157895,  1.84210526,
        2.05263158,  2.26315789,  2.47368421,  2.68421053,  2.89473684,
        3.10526316,  3.31578947,  3.52631579,  3.73684211,  3.94736842,
        4.15789474,  4.36842105,  4.57894737,  4.78947368,  5.        ])

In [175]:
c.shape

(20,)

In [176]:
#change shape of array in-place
c.resize(5,4)
c

array([[ 1.        ,  1.21052632,  1.42105263,  1.63157895],
       [ 1.84210526,  2.05263158,  2.26315789,  2.47368421],
       [ 2.68421053,  2.89473684,  3.10526316,  3.31578947],
       [ 3.52631579,  3.73684211,  3.94736842,  4.15789474],
       [ 4.36842105,  4.57894737,  4.78947368,  5.        ]])

In [177]:
c.shape

(5, 4)

In [181]:
#create array filled with ones
d = np.ones((2,2))
d

array([[ 1.,  1.],
       [ 1.,  1.]])

In [185]:
#create array filled with zeros
e = np.zeros((3,3))
e

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [189]:
#create diagonal matrix with diagonal values =1
f = np.eye(2)
f

array([[ 1.,  0.],
       [ 0.,  1.]])

In [191]:
#extract only the diagonal values from array
np.diag(f)

array([ 1.,  1.])

In [194]:
#create array using repeating list
g = np.array([1,2,3]*5)
g

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [196]:
#repeat elements using repeat
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [23]:
g = np.random.rand(2,3) #this generates a random array
g

array([[ 0.61243315,  0.22618119,  0.67464992],
       [ 0.0344245 ,  0.2948191 ,  0.52865199]])

In [221]:
#stack the above two arrays vertically
i = np.vstack([h,g])
i

array([[ 1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ],
       [ 0.50725359,  0.28610842,  0.98268379],
       [ 0.52425524,  0.23682556,  0.21598467]])

In [222]:
i.shape

(4, 3)

In [224]:
#Now, stack them horizontally
j = np.hstack([h,g])
j

array([[ 1.        ,  1.        ,  1.        ,  0.50725359,  0.28610842,
         0.98268379],
       [ 1.        ,  1.        ,  1.        ,  0.52425524,  0.23682556,
         0.21598467]])

In [225]:
j.shape

(2, 6)

In [24]:
#Array operations
k = np.random.rand(2,2)
l = np.random.rand(2,2)
print(k)
print(l)

[[ 0.02430146  0.14448542]
 [ 0.54428337  0.40332494]]
[[ 0.77574886  0.08747577]
 [ 0.51484157  0.92319888]]


In [25]:
#element wise addition
m = k + l
m

array([[ 0.80005032,  0.23196118],
       [ 1.05912494,  1.32652381]])

In [26]:
#element wise subtraction
n = k-l
n

array([[-0.75144739,  0.05700965],
       [ 0.02944179, -0.51987394]])

In [234]:
#element wise multiplication
o = k*l
o

array([[ 0.38359018,  0.09226875],
       [ 0.39123512,  0.07776932]])

In [27]:
#element wise power
p = k**2
p

array([[ 0.00059056,  0.02087604],
       [ 0.29624438,  0.162671  ]])

In [28]:
#dot product
q = k.dot(l)
q

array([[ 0.09323893,  0.13551456],
       [ 0.62987564,  0.41996073]])

In [241]:
#transpose arrays
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [242]:
a.T #transpose

array([[1, 3],
       [2, 4]])

In [243]:
#check datatype of elements in array
a.dtype

dtype('int32')

In [245]:
#change type using astype
b = a.astype('f')
b.dtype

dtype('float32')

In [246]:
#Math functions in numpy
c = np.array([1,2,3,4,5])

In [248]:
c.sum()

15

In [249]:
c.max()

5

In [250]:
c.mean()

3.0

In [252]:
#return index of maximum value
c.argmax()

4

In [253]:
#return index of minimum value
c.argmin()

0

In [30]:
d = np.arange(10)**2
d

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [31]:
#use index for accessing values
d[2]

4

In [32]:
d[0]

0

In [33]:
d[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [34]:
#use negatives to count from back
d[-1:]

array([81], dtype=int32)

In [35]:
#use two :: to include step size
d[1:10:2] #d[start:stop:stepsize]

array([ 1,  9, 25, 49, 81], dtype=int32)

In [46]:
#multidimensional arrays
e = np.arange(36)
e.resize(6,6)
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
#Access 2nd row and 3rd column
e[1,2]

8

In [48]:
#use : to select range of columns
e[1, 2:6]

array([ 8,  9, 10, 11])

In [49]:
#Select all rows till 2nd row and all columns except last column
e[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [50]:
#select last row and alternate columns
e[-1,::2]

array([30, 32, 34])

In [51]:
#select last row and alternate columns from 3rd column
e[-1,2::2]

array([32, 34])

In [52]:
#select values from array greater than 20
e[e>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [53]:
#Assign element value as 20 if value is greater than 20
e[e>20] = 20
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [45]:
#BE CAREFUL WHILE COPYING ARRAYS
f = e[:3,:3]
f

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [309]:
f[:] = 0
f

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [310]:
e #e also got changed

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [54]:
#copy using copy function
f = e.copy()
f

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [315]:
f[3:,3:] = 0
f

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20,  0,  0,  0],
       [20, 20, 20,  0,  0,  0],
       [20, 20, 20,  0,  0,  0]])

In [316]:
e

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [329]:
#iterating over arrays
g = np.random.randint(1,10,(4,4))
g

array([[9, 7, 1, 4],
       [1, 4, 3, 6],
       [2, 5, 5, 1],
       [2, 2, 9, 9]])

In [330]:
#iterate over row
for row in g:
    print(row)

[9 7 1 4]
[1 4 3 6]
[2 5 5 1]
[2 2 9 9]


In [332]:
#iterate by index
for i in range(len(g)):
    print(g[i])

[9 7 1 4]
[1 4 3 6]
[2 5 5 1]
[2 2 9 9]
