# 1. Python function

In [3]:
#multiply two numbers using a python function
def multiply(x,y):
    z = x*y
    return z

In [4]:
multiply(2,3)

6

# 2. Python types

In [6]:
type(' My name is Rohan')

str

In [7]:
type(1)

int

In [8]:
type(1.0)

float

In [10]:
type(None)

NoneType

In [15]:
type(multiply)

function

# 3. Python sequences

##### Tuples are an immutable data structure which cannot be altered (unlike lists)

In [23]:
a = (1,2,3,4)

In [24]:
type(a)

tuple

#### Lists are mutable objects

In [28]:
b = [1,2,3,4]

In [29]:
type(b)

list

In [30]:
b.append(2.2) #append to list using this function
print(b)

[1, 2, 3, 4, 2.2]


In [32]:
for number in b: #looping through list
    print(number)

1
2
3
4
2.2


In [34]:
for i in range(len(b)): #looping using index of a list
    print(b[i])

1
2
3
4
2.2


In [38]:
[1,2,3] + [1,'abc','de'] #concatenate lists

[1, 2, 3, 1, 'abc', 'de']

In [39]:
[1,2]*3 #repeat lists

[1, 2, 1, 2, 1, 2]

In [40]:
3 in b #in operator to check if required object is in list

True

#### Strings store character objects

In [42]:
x = 'My name is Rohan'

In [43]:
x[0] #Access first letter

'M'

In [45]:
x[0:1] #Still accesses only first letter

'M'

In [47]:
x[0:2] #Accesses two letters

'My'

In [49]:
x[:-1] #Accesses everything except last letter

'My name is Roha'

In [56]:
x[10:] #returns all the characters from 10th position till end

' Rohan'

In [64]:
first = 'Rohan'
last = 'Joseph'

Name = first + ' ' + last #string concatenation

In [65]:
print(Name)

Rohan Joseph


In [69]:
Name.split(' ') #split the words in a string using split function

['Rohan', 'Joseph']

In [74]:
Name.split(' ')[0] #Show the first word

'Rohan'

In [75]:
Name.split(' ')[1] #Show the second word

'Joseph'

In [76]:
Name.split(' ')[-1] #Last word from the end

'Joseph'

In [79]:
#for concatenation convert objects to strings
'Rohan' + str(2)

'Rohan2'

#### Dictionaries link keys and values

In [16]:
c = {"Name" : "Rohan", "Height" : 176}

In [82]:
type(c)

dict

In [85]:
print(c)

{'Name': 'Rohan', 'Height': 176}


In [84]:
c['Name'] #Access Name

'Rohan'

In [86]:
c['Height']

176

In [87]:
#print all the keys
for i in c:
    print(i)

Name
Height


In [92]:
#print all the values
for i in c.values():
    print(i)

Rohan
176


In [93]:
#iterate over all the items
for name, height in c.items():
    print(name)
    print(height)

Name
Rohan
Height
176


In [99]:
#Unpacking a list into different variables
a,b = ('abc','def')
print(a)
print(b)

abc
def


# 4. Python dates and times

In [100]:
import datetime as dt
import time as tm

In [103]:
tm.time() #print current time in seconds from January 1, 1970

1532483980.5827992

In [109]:
dtnow = dt.datetime.fromtimestamp(tm.time()) #convert timestamp to datetime

In [111]:
dtnow.year

2018

In [112]:
dtnow.month

7

In [119]:
delta = dt.timedelta(days=100)

In [115]:
today = dt.date.today()

In [116]:
today

datetime.date(2018, 7, 25)

In [120]:
today - delta #subtract 100 days from today's date

datetime.date(2018, 4, 16)

# 5. Map function

In [135]:
a = [1,2,3,10]
b = [5,6,2,9]

c = map(min,a,b) #Find the minimum between two pairs of lists


In [136]:
for item in c:
    print(item) #print the minimum of the pairs

1
2
2
9


# 6. Lambda function

In [145]:
function = lambda a,b,c : a+b+c #function to add three numbers

In [146]:
function(2,2,3)

7

# 7. List comprehension

In [148]:
#return even numbers from 1 to 100

even=[]
for i in range(100):
    if i%2 ==0:
        even.append(i)
    else:
        None
        

In [149]:
print(even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [154]:
#Let's do the same using list comprehension

even = [i for i in range(100) if i%2==0]
print(even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


# 8. Numpy

In [155]:
import numpy as np #import

In [157]:
#create numpy array
np.array([1,2,3])

array([1, 2, 3])

In [160]:
a = np.array([[1,2,3],[4,5,6]]) #create multi dimensional array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [161]:
#shape of the array
a.shape

(2, 3)

In [163]:
#evenly spaced values between the interval
b = np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [170]:
#create new shape of data
b.reshape(5,3)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [174]:
#get evenly spaced numbers between specified interval
c = np.linspace(1,5,20)
c

array([ 1.        ,  1.21052632,  1.42105263,  1.63157895,  1.84210526,
        2.05263158,  2.26315789,  2.47368421,  2.68421053,  2.89473684,
        3.10526316,  3.31578947,  3.52631579,  3.73684211,  3.94736842,
        4.15789474,  4.36842105,  4.57894737,  4.78947368,  5.        ])

In [175]:
c.shape

(20,)

In [176]:
#change shape of array in-place
c.resize(5,4)
c

array([[ 1.        ,  1.21052632,  1.42105263,  1.63157895],
       [ 1.84210526,  2.05263158,  2.26315789,  2.47368421],
       [ 2.68421053,  2.89473684,  3.10526316,  3.31578947],
       [ 3.52631579,  3.73684211,  3.94736842,  4.15789474],
       [ 4.36842105,  4.57894737,  4.78947368,  5.        ]])

In [177]:
c.shape

(5, 4)

In [181]:
#create array filled with ones
d = np.ones((2,2))
d

array([[ 1.,  1.],
       [ 1.,  1.]])

In [185]:
#create array filled with zeros
e = np.zeros((3,3))
e

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [189]:
#create diagonal matrix with diagonal values =1
f = np.eye(2)
f

array([[ 1.,  0.],
       [ 0.,  1.]])

In [191]:
#extract only the diagonal values from array
np.diag(f)

array([ 1.,  1.])

In [194]:
#create array using repeating list
g = np.array([1,2,3]*5)
g

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [196]:
#repeat elements using repeat
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [215]:
h = np.ones((2,3))
g = np.random.rand(2,3) #this generates a random array

In [221]:
#stack the above two arrays vertically
i = np.vstack([h,g])
i

array([[ 1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ],
       [ 0.50725359,  0.28610842,  0.98268379],
       [ 0.52425524,  0.23682556,  0.21598467]])

In [222]:
i.shape

(4, 3)

In [224]:
#Now, stack them horizontally
j = np.hstack([h,g])
j

array([[ 1.        ,  1.        ,  1.        ,  0.50725359,  0.28610842,
         0.98268379],
       [ 1.        ,  1.        ,  1.        ,  0.52425524,  0.23682556,
         0.21598467]])

In [225]:
j.shape

(2, 6)

In [228]:
#Array operations
k = np.random.rand(2,2)
l = np.random.rand(2,2)
print(k)
#print(l)

[[ 0.42443005  0.28611242]
 [ 0.65396499  0.57360354]]
[[ 0.90377716  0.32249125]
 [ 0.59825087  0.13558027]]


In [230]:
#element wise addition
m = k + l
m

array([[ 1.32820721,  0.60860367],
       [ 1.25221586,  0.70918381]])

In [232]:
#element wise subtraction
n = k-l
n

array([[-0.47934711, -0.03637883],
       [ 0.05571412,  0.43802327]])

In [234]:
#element wise multiplication
o = k*l
o

array([[ 0.38359018,  0.09226875],
       [ 0.39123512,  0.07776932]])

In [236]:
#element wise power
p = k**2
p

array([[ 0.18014086,  0.08186032],
       [ 0.42767021,  0.32902102]])

In [238]:
#dot product
q = k.dot(l)
q

array([[ 0.55475719,  0.17566617],
       [ 0.93419744,  0.28866731]])

In [241]:
#transpose arrays
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [242]:
a.T #transpose

array([[1, 3],
       [2, 4]])

In [243]:
#check datatype of elements in array
a.dtype

dtype('int32')

In [245]:
#change type using astype
b = a.astype('f')
b.dtype

dtype('float32')

In [246]:
#Math functions in numpy
c = np.array([1,2,3,4,5])

In [248]:
c.sum()

15

In [249]:
c.max()

5

In [250]:
c.mean()

3.0

In [252]:
#return index of maximum value
c.argmax()

4

In [253]:
#return index of minimum value
c.argmin()

0

In [262]:
d = np.arange(10)**2
d

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [263]:
#use index for accessing values
d[2]

4

In [264]:
d[0]

0

In [266]:
d[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [276]:
#use negatives to count from back
d[-1:]

array([81], dtype=int32)

In [280]:
#use two :: to include step size
d[1:10:2] #d[start:stop:stepsize]

array([ 1,  9, 25, 49, 81], dtype=int32)

In [282]:
#multidimensional arrays
e = np.arange(36)
e.resize(6,6)
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [284]:
#Access 2nd row and 3rd column
e[1,2]

8

In [286]:
#use : to select range of columns
e[1, 2:6]

array([ 8,  9, 10, 11])

In [287]:
#Select all rows till 2nd row and all columns except last column
e[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [290]:
#select last row and alternate columns
e[-1,::2]

array([30, 32, 34])

In [291]:
#select last row and alternate columns from 3rd column
e[-1,2::2]

array([32, 34])

In [292]:
#select values from array greater than 20
e[e>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [294]:
#Assign element value as 20 if value is greater than 20
e[e>20] = 20
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [308]:
#BE CAREFUL WHILE COPYING ARRAYS
f = e[:3,:3]
f

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [309]:
f[:] = 0
f

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [310]:
e #e also got changed

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [313]:
#copy using copy function
f = e.copy()
f

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [315]:
f[3:,3:] = 0
f

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20,  0,  0,  0],
       [20, 20, 20,  0,  0,  0],
       [20, 20, 20,  0,  0,  0]])

In [316]:
e

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [329]:
#iterating over arrays
g = np.random.randint(1,10,(4,4))
g

array([[9, 7, 1, 4],
       [1, 4, 3, 6],
       [2, 5, 5, 1],
       [2, 2, 9, 9]])

In [330]:
#iterate over row
for row in g:
    print(row)

[9 7 1 4]
[1 4 3 6]
[2 5 5 1]
[2 2 9 9]


In [332]:
#iterate by index
for i in range(len(g)):
    print(g[i])

[9 7 1 4]
[1 4 3 6]
[2 5 5 1]
[2 2 9 9]
